apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-test
  name: code-test-deployment
  namespace: codetest
spec:
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: code-test
  template:
    metadata:
      labels:
        app: code-test
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: kumarmanvit/codeexample:1.1
          imagePullPolicy: Always
          name: code-test
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 1Gi
              cpu: "0.5"
            limits:
              memory: 2Gi
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /codetest
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 20
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /codetest
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 20
