apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: kustomize
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: registry.hub.docker.com/kumarmanvit/codeexample
    newTag: 1.1