apiVersion: v1
kind: Service
metadata:
  name: code-test
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: code-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008